#pragma config(Sensor, dgtl1,  elevatorUpB,    sensorTouch)
#pragma config(Sensor, dgtl2,  elevatorDownB,  sensorTouch)
#pragma config(Sensor, dgtl3,  semiLoaderInB,  sensorTouch)
#pragma config(Sensor, dgtl4,  semiLoaderOutB, sensorTouch)
#pragma config(Sensor, dgtl5,  dumperB,        sensorTouch)
#pragma config(Sensor, dgtl12, touch,          sensorTouch)
#pragma config(Motor,  port2,           elevatorM,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           semiLoaderM,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           dumperM,       tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int elevatorState = 1;
int semiLoaderState = 1;
int dumperState = 0;
void moveElevator(int state, int speed) {
	switch(state) {
	case 0:
		motor[elevatorM] = -speed;
		while(SensorValue(elevatorDownB) != 1) {
		}
		motor[elevatorM] = 20;
		delay(200);
		motor[elevatorM] = 0;
		elevatorState = 0;
		break;
	case 1:
		motor[elevatorM] = speed;
		while(SensorValue(elevatorUpB) != 1) {
		}
		motor[elevatorM] = 0;
		elevatorState = 1;
		break;
	case 2:
		if(elevatorState == 1) {
			motor[elevatorM] = -25;
			delay(2000);
			motor[elevatorM] = 0;
			elevatorState = 2;
		}
		break;
	case 3:
		if(elevatorState == 0) {
			motor[elevatorM] = 50;
			delay(850);
			motor[elevatorM] = 0;
			elevatorState = 3;
		}
		break;
	case 4:
		if(elevatorState == 0) {
			motor[elevatorM] = 100;
			delay(1400);
			motor[elevatorM] = 0;
			elevatorState = 4;
		}
		break;
	}
}

void actuateDumper(int state) {
	switch(state) {
	case 0:
		motor[dumperM] = -70;
		while(SensorValue(dumperB) != 1) {
		}
		motor[dumperM] = 0;
		dumperState = 0;
		break;
	case 1:
		if(dumperState == 0) {
			motor[dumperM] = 100;
			delay(9000);
			motor[dumperM] = 0;
			dumperState = 1;
		}
	case 2:
		if(dumperState == 1) {
			motor[dumperM] = -70;
			delay(5000);
			motor[dumperM] = 0;
			dumperState = 2;
		}
		break;
	}
}

void actuateSemiLoader(int state, int speed) {
	switch(state) {
	case 0:
		motor[semiLoaderM] = -speed;
		while(SensorValue(semiLoaderInB) != 1) {
		}
		motor[semiLoaderM] = 0;
		semiLoaderState = 0;
		break;
	case 1:
		motor[semiLoaderM] = speed;
		while(SensorValue(semiLoaderOutB) != 1) {
		}
		motor[semiLoaderM] = 0;
		semiLoaderState = 1;
		break;
	case 2:
		if(semiLoaderState == 0) {
			motor[semiLoaderM] = 75;
			delay(6800);
			motor[semiLoaderM] = 30;
			delay(500);
			motor[semiLoaderM] = 0;
			semiLoaderState = 2;
		}
	case 3:
		if(semiLoaderState == 1) {
			motor[semiLoaderM] = -75;
			delay(5000);
			motor[semiLoaderM] = 0;
			semiLoaderState = 3;
		}
		break;
	}
}

void loadContainer() {
	moveElevator(0, 35);
	moveElevator(3, 70);
	actuateSemiLoader(0, 75);
	actuateSemiLoader(2, 75);
	motor[semiLoaderM] = -75;
	delay(1000);
	motor[semiLoaderM] = 0;
	moveElevator(1, 100);
	waitUntil(SensorValue(touch) == 1);
	moveElevator(0, 35);
	actuateSemiLoader(1, 75);
	moveElevator(4, 75);
		actuateSemiLoader(3, 75);
	motor[semiLoaderM] = 75;
	delay(250);
	motor[semiLoaderM] = 0;
	delay(5000);
	actuateSemiLoader(0, 75);
}


task main() {
	while(true) {
		/*if(SensorValue(touch) == 1) {
		if(semiLoaderState == 0) {
		actuateSemiLoader(2, 75);
		}
		else {
		actuateSemiLoader(0, 75);
		}
		delay(500);
		}*/
		/*if(SensorValue(touch) == 1) {
		if(elevatorState == 0) {
		moveElevator(1, 100);
		}
		else {
		moveElevator(0, 25);
		}
		delay(500);
		}
		*/
		if(SensorValue(touch) == 1) {
			loadContainer();
		}
	}
}
