#pragma config(Sensor, in1,    lineLeft,       sensorLineFollower)
#pragma config(Sensor, in2,    lineCenter,     sensorLineFollower)
#pragma config(Sensor, in3,    lineRight,      sensorLineFollower)
#pragma config(Sensor, dgtl1,  touch,          sensorTouch)
#pragma config(Motor,  port2,           driveLeftM,   tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           driveRightM,   tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           steerS,        tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int lineThresh = 1500;
int loopCount;
int const offsetStarting = 40;
int const offsetIncrement = 5;
int offset;
/*task eStop() {
	delay(2000);
	while(true) {
		if(vexRT(Btn8D) == 1 || SensorValue(touch) == 1) {
			delay(300);
			while(true) {
				if(vexRT(Btn8D) == 1 || SensorValue(touch) == 1) {
					break;
				}
				motor[driveLeftM] = 0;
				motor[driveRightM] = 0;
				motor[steerS] = 0;
			}
			delay(1000);
			motor[driveLeftM] = 100;
			motor[driveRightM] = 100;
		}
	}
}*/
task main()
{
	while(true) {
		motor[driveLeftM] = vexRT[CH3];
		motor[driveRightM] = vexRT[CH3];
		motor[steerS] = vexRT[CH1];
	}
}
	/*
	waitUntil(SensorValue(touch) == 1 || vexRT(Btn8D) == 1);
	startTask(eStop);
	motor[driveLeftM] = 100;
	motor[driveRightM] = 100;
	while(true) {
		if(SensorValue(lineLeft) > lineThresh) {
			motor[steerS] = -offsetStarting;
			motor[driveLeftM] = 70;
			offset = -offsetStarting;
			while(SensorValue(lineCenter) < lineThresh) {
				delay(2);
				loopCount++;
				if(loopCount == 50) {
					loopCount = 0;
					offset = offset - offsetIncrement;
					motor[steerS] = offset;
				}
			}
			offset = 0;
			motor[steerS] = offset;
			motor[driveLeftM] = 100;
		}

		if(SensorValue(lineRight) > lineThresh) {
			motor[steerS] = offsetStarting;
			motor[driveRightM] = 70;
			offset = offsetStarting;
			while(SensorValue(lineCenter) < lineThresh) {
				delay(2);
				loopCount++;
				if(loopCount == 50) {
					loopCount = 0;
					offset = offset + offsetIncrement;
					motor[steerS] = offset;
				}
			}
			offset = 0;
			motor[steerS] = offset;
			motor[driveRightM] = 100;
		}
	}
}*/
